import {
    ALERTS_API,
    APPOINTMENT_API,
    ASSISTANT_API,
    DOCTORS_API,
    FEEDBACK_API,
    MEDICATIONS_API,
    PATIENTS_API,
    PAYMENTS_API,
    PRESCRIPTIONS_API,
    SUBSCRIPTIONS_API,
    VITALS_API,
    WALLET_API,
} from '@/shared/constants/api.constants'

export const PATIENT_ENDPOINTS = {
    REGISTER: `${PATIENTS_API}/register`,
    DOCTORS: DOCTORS_API,
    DOCTOR_SLOTS: (doctorId: string) => `${DOCTORS_API}/${doctorId}/slots`,
    PROFILE: `${PATIENTS_API}/me`,
    CARE_TEAM: `${PATIENTS_API}/me/care-team`,
    APPOINTMENTS: `${APPOINTMENT_API}/patient`,
    CREATE_APPOINTMENT: APPOINTMENT_API,
    APPOINTMENT_BY_ID: (appointmentId: string) => `${APPOINTMENT_API}/${appointmentId}`,
    APPOINTMENT_CANCEL: (id: string) => `${APPOINTMENT_API}/${id}/cancel`,
    APPOINTMENT_RETRY_PAYMENT: (id: string) => `${APPOINTMENT_API}/${id}/retry-payment`,
    APPOINTMENT_RESCHEDULE: (id: string) => `${APPOINTMENT_API}/${id}/reschedule`,
    WALLET: WALLET_API,
    PAYMENT_VERIFY: `${PAYMENTS_API}/verify`,
    WALLET_TOPUP_ORDER: `${PAYMENTS_API}/wallet-topup/order`,
    WALLET_TOPUP_VERIFY: `${PAYMENTS_API}/wallet-topup/verify`,
    SUBSCRIPTION_ME: `${SUBSCRIPTIONS_API}/me`,
    SUBSCRIPTIONS: SUBSCRIPTIONS_API,
    SUBSCRIPTION_VERIFY: `${SUBSCRIPTIONS_API}/verify`,
    SUBSCRIPTION_CANCEL: (subscriptionId: string) => `${SUBSCRIPTIONS_API}/${subscriptionId}/cancel`,
    MEDICATIONS_ME: `${MEDICATIONS_API}/me`,
    ALERT_COUNT: `${ALERTS_API}/me/count`,
    VITAL_SCHEDULES: `${VITALS_API}/schedules/me`,
    PRESCRIPTIONS_BY_PATIENT: (patientId: string) => `${PRESCRIPTIONS_API}/patient/${patientId}`,
    FEEDBACK: FEEDBACK_API,
    ASSISTANT_CHAT: `${ASSISTANT_API}/chat`,
} as const
