export const SPECIALIZATIONS = [
    'General Medicine',
    'Cardiology',
    'Dermatology',
    'Neurology',
    'Orthopedics',
    'Pediatrics',
    'Psychiatry',
    'Gynecology',
    'Ophthalmology',
    'ENT',
    'Urology',
    'Gastroenterology',
    'Endocrinology',
    'Pulmonology',
    'Nephrology',
    'Oncology',
    'Radiology',
    'Anesthesiology',
    'Emergency Medicine',
    'General Surgery',
    'Plastic Surgery',
    'Physical Medicine & Rehabilitation',
    'Rheumatology',
    'Infectious Disease',
    'Geriatrics',
    'Sports Medicine',
    'Public Health',
]
