export const TOKENS = {
    IUserRepository: Symbol('IUserRepository'),
    IDoctorRepository: Symbol('IDoctorRepository'),
    IDoctorAvailabilityRepository: Symbol('IDoctorAvailabilityRepository'),
    IAvailabilityNotificationService: Symbol('IAvailabilityNotificationService'),
    IDoctorService: Symbol('IDoctorService'),
    ICaregiverRepository: Symbol('ICaregiverRepository'),
    ICaregiverService: Symbol('ICaregiverService'),
    IPatientRepository: Symbol('IPatientRepository'),
    IPatientService: Symbol('IPatientService'),
    IAuthService: Symbol('IAuthService'),
    IOtpService: Symbol('IOtpService'),
    IAdminRepository: Symbol('IAdminRepository'),
    IAdminService: Symbol('IAdminService'),
    IAppointmentRepository: Symbol('IAppointmentRepository'),
    IAppointmentService: Symbol('IAppointmentService'),
    IPaymentRepository: Symbol('IPaymentRepository'),
    IPaymentService: Symbol('IPaymentService'),
    IWalletRepository: Symbol('IWalletRepository'),
    IWalletService: Symbol('IWalletService'),
}
